config/routes.rb
Rails.application.routes.draw do
  resources :pageparameters
  root 'home#index'
  get '/detail/:id', to: 'home#detail'
  resources :gifdays
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gifday.rb
class Gifday < ApplicationRecord
end

app/models/pageparameter.rb
class Pageparameter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gifdays_controller.rb
class GifdaysController < ApplicationController
  before_action :set_gifday, only: [:show, :edit, :update, :destroy]

  # GET /gifdays
  # GET /gifdays.json
  def index
    @gifdays = Gifday.all
  
  end

  # GET /gifdays/1
  # GET /gifdays/1.json
  def show
  end

  # GET /gifdays/new
  def new
    @gifday = Gifday.new
  end

  # GET /gifdays/1/edit
  def edit
  end

  # POST /gifdays
  # POST /gifdays.json
  def create
    @gifday = Gifday.new(gifday_params)

    respond_to do |format|
      if @gifday.save
        format.html { redirect_to @gifday, notice: 'Gifday was successfully created.' }
        format.json { render :show, status: :created, location: @gifday }
      else
        format.html { render :new }
        format.json { render json: @gifday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifdays/1
  # PATCH/PUT /gifdays/1.json
  def update
    respond_to do |format|
      if @gifday.update(gifday_params)
        format.html { redirect_to @gifday, notice: 'Gifday was successfully updated.' }
        format.json { render :show, status: :ok, location: @gifday }
      else
        format.html { render :edit }
        format.json { render json: @gifday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifdays/1
  # DELETE /gifdays/1.json
  def destroy
    @gifday.destroy
    respond_to do |format|
      format.html { redirect_to gifdays_url, notice: 'Gifday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gifday
      @gifday = Gifday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gifday_params
      params.require(:gifday).permit(:title, :body, :daynumber, :companyname)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gifdays = Gifday.all
    @pageparameter =  Pageparameter.find(1)
  end

  def detail
    @gifday = Gifday.find(params[:id])
    @pageparameter =  Pageparameter.find(1)
  end
end

app/controllers/pageparameters_controller.rb
class PageparametersController < ApplicationController
  before_action :set_pageparameter, only: [:show, :edit, :update, :destroy]

  # GET /pageparameters
  # GET /pageparameters.json
  def index
    @pageparameters = Pageparameter.all
  end

  # GET /pageparameters/1
  # GET /pageparameters/1.json
  def show
  end

  # GET /pageparameters/new
  def new
    @pageparameter = Pageparameter.new
  end

  # GET /pageparameters/1/edit
  def edit
  end

  # POST /pageparameters
  # POST /pageparameters.json
  def create
    @pageparameter = Pageparameter.new(pageparameter_params)

    respond_to do |format|
      if @pageparameter.save
        format.html { redirect_to @pageparameter, notice: 'Pageparameter was successfully created.' }
        format.json { render :show, status: :created, location: @pageparameter }
      else
        format.html { render :new }
        format.json { render json: @pageparameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pageparameters/1
  # PATCH/PUT /pageparameters/1.json
  def update
    respond_to do |format|
      if @pageparameter.update(pageparameter_params)
        format.html { redirect_to @pageparameter, notice: 'Pageparameter was successfully updated.' }
        format.json { render :show, status: :ok, location: @pageparameter }
      else
        format.html { render :edit }
        format.json { render json: @pageparameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pageparameters/1
  # DELETE /pageparameters/1.json
  def destroy
    @pageparameter.destroy
    respond_to do |format|
      format.html { redirect_to pageparameters_url, notice: 'Pageparameter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pageparameter
      @pageparameter = Pageparameter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pageparameter_params
      params.require(:pageparameter).permit(:title, :notice)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifdays_helper.rb
module GifdaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pageparameters_helper.rb
module PageparametersHelper
end

app/views/gifdays/_form.html.erb
<%= form_with(model: gifday, local: true) do |form| %>
  <% if gifday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gifday.errors.count, "error") %> prohibited this gifday from being saved:</h2>

      <ul>
      <% gifday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title, id: :gifday_title %>
  </div>

  <div class="field">
    <%= form.label :body %><br />
    <%= form.text_area :body, id: :gifday_body, size: '80x5' %>
  </div>

  <div class="field">
    <%= form.label :companyname %><br />
    <%= form.text_field :companyname, id: :gifday_companyname %>
  </div>
  <br /><br />
  <div class="actions">
    <%= form.submit %>
  </div>

  <br /><br />
  <br /><br />
  <br /><br />
<% end %>

app/views/gifdays/edit.html.erb
<h1>Editing Gifday</h1>

<%= render 'form', gifday: @gifday %>

<%= link_to 'Show', @gifday %> |
<%= link_to 'Back', gifdays_path %>

app/views/gifdays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administation</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Companyname</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifdays.each do |gifday| %>
      <tr>
        <td><%= gifday.title %></td>
        <td><%= gifday.companyname %></td>
        <td><%= link_to 'Edit', edit_gifday_path(gifday) %> | </td>
        <td><%= link_to 'Destroy', gifday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gifday', new_gifday_path %>

app/views/gifdays/new.html.erb
<h1>New Gifday</h1>

<%= render 'form', gifday: @gifday %>

<%= link_to 'Back', gifdays_path %>

app/views/gifdays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gifday.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @gifday.body %>
</p>

<p>
  <strong>Daynumber:</strong>
  <%= @gifday.daynumber %>
</p>

<p>
  <strong>Companyname:</strong>
  <%= @gifday.companyname %>
</p>

<%= link_to 'Edit', edit_gifday_path(@gifday) %> |
<%= link_to 'Back', gifdays_path %>

app/views/home/detail.html.erb
<div class="container">

    <div id="hd">
      <h1>INVERCARGILL KINDNESS ADVENT CALENDAR</h1>
    </div>

    <div id="bd">
        <div class="back-button"> <%= link_to 'Back', "/" %>
| <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.greenlightsolutions.nz%2F&amp;src=sdkpreparse">Share</a>
        </div>
        <div id="day-list">

          <p class="center">
            <img class="product-img" src="/images/p/<%= @gifday.id %>.jpg"
          </p>

          <p class="center">

            <%= @gifday.body %>
          </p>
        </div>

<div class="box-bottom"></div>
    </div>

    <div id="ft">
      copyright all reserved.
    </div>

</div>

app/views/home/index.html.erb
<div class="container">

    <div id="hd">
      <h1><%= @pageparameter.title %></h1>
    </div>

    <div id="bd">

      <div class="notice-text">
        <%= @pageparameter.notice %>
      </div>

        <div id="day-list">
        <% @gifdays.each do |gifday| %>
          <div class="day-box"><%= link_to gifday.title, "/detail/#{gifday.id}" %></div>
        <% end %>
        </div>

          <div class="box-bottom"></div>
    </div>

    <div id="ft">
      Copyright all Greenlight Innovations Limited reserved.
    </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invscalender</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/gifdays.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invscalender</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

        <div id="bd">
    <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/layouts/pageparameters.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invscalender</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

        <div id="bd">
    <%= yield %>
    <div class="box-bottom"></div>
    <div class="box-bottom"></div>
        </div>
    </div>
  </body>
</html>

app/views/pageparameters/_form.html.erb
<%= form_with(model: pageparameter, local: true) do |form| %>
  <% if pageparameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pageparameter.errors.count, "error") %> prohibited this pageparameter from being saved:</h2>

      <ul>
      <% pageparameter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_area :title, id: :pageparameter_title, size: '80x5' %>
  </div>

  <div class="field">
    <%= form.label :notice %><br />
    <%= form.text_area :notice, id: :pageparameter_notice, size: '80x5' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pageparameters/edit.html.erb
<h1>Editing Pageparameter</h1>

<%= render 'form', pageparameter: @pageparameter %>

app/views/pageparameters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pageparameters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pageparameters.each do |pageparameter| %>
      <tr>
        <td><%= pageparameter.title %></td>
        <td><%= pageparameter.notice %></td>
        <td><%= link_to 'Show', pageparameter %></td>
        <td><%= link_to 'Edit', edit_pageparameter_path(pageparameter) %></td>
        <td><%= link_to 'Destroy', pageparameter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pageparameter', new_pageparameter_path %>

app/views/pageparameters/new.html.erb
<h1>New Pageparameter</h1>

<%= render 'form', pageparameter: @pageparameter %>

<%= link_to 'Back', pageparameters_path %>

app/views/pageparameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pageparameter.title %>
</p>

<p>
  <strong>Notice:</strong>
  <%= @pageparameter.notice %>
</p>